module.exports = Object.freeze({
    TAG_REQTYPE_SALE : 0,
    TAG_REQTYPE_VOID : 1,
    TAG_REQTYPE_REFUND : 2,
    TAG_REQTYPE_SETTLEMENT : 5,
    TAG_REQTYPE_PREAUTH : 8,
    TAG_REQTYPE_SALECOMPLETE : 9,
    TAG_REQTYPE_TIPADJUST : 15,
    TAG_REQTYPE : -1
});