module.exports = Object.freeze({
    SERIAL_UPLOAD_PACKET : 1,
    ISP_UPLOAD_PACKET:2,
    NAC_UPLOAD_PACKET:3,
    GPRS_UPLOAD_PACKET:4,
    ETHERNET_UPLOAD_PACKET:5,
    TERMINAL_PARAM_UPLOAD_PACKET:6,
    MASTER_PARAM_UPLOAD_PACKET:7,
    AUTOSETTLE_UPLOAD_PACKET:8,
});